name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        env:
          CI: false  # Отключение режима CI
        run: npm run build --if-present

      - name: Run Tests
        run: npm test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Verify build directory
        run: |
          if [ ! -d "build" ]; then
            echo "Build directory does not exist!";
            exit 1;
          fi

      - name: Set up Git
        run: |
          git config --global user.name "danos_011"
          git config --global user.email "d_osetrov@mail.ru"

      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          gh-pages -d build -r https://x-access-token:${{ secrets.GH_ACCESS_TOKEN }}@github.com/${{ github.repository }} -b gh-pages
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}