name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        env:
          CI: false
        run: |
          npm run build
          echo "Listing contents of the build directory after build:"
          ls -la build || echo "Build directory does not exist after build!"

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: List files in the working directory after downloading artifact
        run: ls -la

      - name: List files in the build directory after download
        run: |
          if [ -d "build" ]; then
            echo "Build directory exists:"
            ls -la build
          else
            echo "Build directory does not exist after downloading artifact!"
            exit 1
          fi

      - name: Set up Git
        run: |
          git config --global user.name "danos011"
          git config --global user.email "d_osetrov@mail.ru"

      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          gh-pages -d build -r https://x-access-token:${{ secrets.GH_ACCESS_TOKEN }}@github.com/${{ github.repository }} -b gh-pages
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}